<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LagoVista.IoT.Billing.Managers" Version="6.0.1" />
    <PackageVersion Include="LagoVista.IoT.Deployment.Admin" Version="6.0.1" />
    <PackageVersion Include="LagoVista.IoT.Web.Common" Version="6.0.2" />
    <PackageVersion Include="LagoVista.ProjectManagement.Core" Version="6.0.1" />
    <PackageVersion Include="LagoVista.UserAdmin" Version="6.0.2" />
  </ItemGroup>
</Project>
