// --- BEGIN CODE INDEX META (do not edit) ---
// ContentHash: 8a460acf411c1854d129ca0d9418ff5eea59246df71caddf6734d21d96c28ae3
// IndexVersion: 2
// --- END CODE INDEX META ---
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.UserAdmin {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserAdminRestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserAdminRestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.UserAdmin.UserAdminRestResources", typeof(UserAdminRestResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You have requested to have your password reset.&lt;/p&gt;
        ///
        ///&lt;p&gt;Please Reset your Password by clicking this &lt;a href=&apos;[CALLBACK_URL]&apos;&gt;browser link&lt;/a&gt; on your desktop or &lt;a href=&apos;[MOBILE_CALLBACK_URL]&apos;&gt;mobile link&lt;/a&gt; on your mobile phone.&lt;/p&gt;
        ///
        ///&lt;p&gt;If you did not request your password to be changed, you can safely ignore this email.&lt;/p&gt;.
        /// </summary>
        internal static string Email_ResetPassword_Body {
            get {
                return ResourceManager.GetString("Email_ResetPassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password on your [APP_NAME] account..
        /// </summary>
        internal static string Email_ResetPassword_Subject {
            get {
                return ResourceManager.GetString("Email_ResetPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error sending your reset password link, please try again later..
        /// </summary>
        internal static string Email_RestPassword_ErrorSending {
            get {
                return ResourceManager.GetString("Email_RestPassword_ErrorSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you for signing up, for your added security we need you to please confirm your email address&lt;/p&gt;
        ///
        ///&lt;p&gt;Please confirm your account by clicking this &lt;a href=&apos;[CALLBACK_URL]&apos;&gt;browser link&lt;/a&gt; on your desktop or &lt;a href=&apos;[MOBILE_CALLBACK_URL]&apos;&gt;mobile link&lt;/a&gt; on your mobile phone.&lt;/p&gt;.
        /// </summary>
        internal static string Email_Verification_Body {
            get {
                return ResourceManager.GetString("Email_Verification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your [APP_NAME] account.
        /// </summary>
        internal static string Email_Verification_Subject {
            get {
                return ResourceManager.GetString("Email_Verification_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a user with that User Id.
        /// </summary>
        internal static string Err_PwdChange_CouldNotFindUser {
            get {
                return ResourceManager.GetString("Err_PwdChange_CouldNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is Required..
        /// </summary>
        internal static string Err_PwdChange_NewPassword_Missing {
            get {
                return ResourceManager.GetString("Err_PwdChange_NewPassword_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is Required..
        /// </summary>
        internal static string Err_PwdChange_OldPassword_Missing {
            get {
                return ResourceManager.GetString("Err_PwdChange_OldPassword_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pass in the Id (not user name) of the user that is requesting to change the password..
        /// </summary>
        internal static string Err_PwdChange_UserId_Missing {
            get {
                return ResourceManager.GetString("Err_PwdChange_UserId_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not find a user with that email address..
        /// </summary>
        internal static string Err_ResetPwd_CouldNotFindUser {
            get {
                return ResourceManager.GetString("Err_ResetPwd_CouldNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can not change your password at this time.  Please logout, then log back in to change your password..
        /// </summary>
        internal static string Err_UserId_DoesNotMatch {
            get {
                return ResourceManager.GetString("Err_UserId_DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the code you entered was not the code that was sent to the phone, please try again..
        /// </summary>
        internal static string SMS_CouldNotVerify {
            get {
                return ResourceManager.GetString("SMS_CouldNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code [CODE] in [APP_NAME].
        /// </summary>
        internal static string SMS_Verification_Body {
            get {
                return ResourceManager.GetString("SMS_Verification_Body", resourceCulture);
            }
        }
    }
}
